### ISSUE TITLE
Moving to London: what you need to know as a developer

### ISSUE THREAD

**Issue by mtt87** [ItalianiDigitaliLondra/WhatWeWantToDo#2]
Daniele suggested the last dinner to write a guide for Italian developer that are planning to move to London.

A few topic we could discuss:
- Finding a room
- Salary
- Meetup/Area
- Life cost

Feel free to suggest

**Comment by fabiocicerchia** [comment]
This link can be a good introduction, it's a guide called "Primo Approdo" made by the Italian Consulate in London.
http://www.conslondra.esteri.it/NR/rdonlyres/9C3255D1-39AB-4FC4-BEA7-C2A752E28E62/0/ManualeOrientamentoDEF6.pdf

**Comment by mtt87** [comment]
It's good we can keep it as a link but it would be cool to write something on our own, more tailored for a developer or somebody working in IT.

:smile:

**Comment by danieledangeli** [comment]
Yes I really like the idea to introduce London life (for developer/startupper) and give some job advices. 
The key of this idea is the statement that I said to Mattia during our last meetup: 

> Would be really useful for me if one year ago (when I moved to London) someone would have enriched  my knowledge about the London IT Jobs"

So the base idea is to give a message about us and give some email, ref, profiles about people that could help you: e.g
-  startupper frontend (Mattia etc ect)
-  startupper python java (Alessio etc ect)
-  ....
-  ....

**Comment by gcalore** [comment]
We already have the means to contact people and ask questions with our facebook group. This should be the place for general advice and a reminder that we are not misterious people but you can actually meet us :)

Also, there are several generic guides on how to survive London, do we want to write our own or do we just focus on the developer side of things? I personally think we can write our own better version :)

**Comment by mtt87** [comment]
Okay I got the message of @danieledangeli and I think it could be a tag system where we can tag our skills so if somebody is looking for advice for example about PHP they will see that we have X members working with PHP everyday that may be able to suggest.

But I agree with @gcalore that we shouldn't build anything to make the discussion happen on the website, because there is already the Facebook group and it's okay for what we need right now.

**Comment by gcalore** [comment]
My post wasn't about keeping all the talk in the facebook group (we might want a forum board if we keep growing?), it's more about encouraging people to meet IRL with the whole group, especially since we're in the same city.

I'm worried that if we give big exposition to individual people and their contacts, we encourage newcomers to write to just one of us and be done with it, instead of engaging with the community we are building.

So instead of giving personal contacts I'm thinking something along the lines of "if you have questions, join our facebook group and come to our events".

It's not that big of a deal, I was just trying to think in terms of what we want to achieve.

[Off-topic] that reminds me: what is our purpose, and do what we want to achieve?
Where we are going and what do we want to do at a community level?
I'm sure each of us have ideas about this topic, but we need to clarify this to ourselves, and possibly write down something (a mission statement of sorts, and some strategic planning, to keep using the business analogy).
I'd like to discuss this IRL with you guys, but if you feel like it we can open a new issue here or discuss it on facebook.
